//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLS
    {
        public int ID_BILL { get; set; }
        public int ID_ORDER { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public string PAYMENT_STATUS { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
    }
}
