//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COMPUTER_SHOP : DbContext
    {
        private static COMPUTER_SHOP _context;
        public static COMPUTER_SHOP GetContext()
        {
            if (_context == null)
                _context = new COMPUTER_SHOP();
            return _context;
        }
        public COMPUTER_SHOP()
            : base("name=COMPUTER_SHOP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILLS> BILLS { get; set; }
        public virtual DbSet<CATALOGS> CATALOGS { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<ViewORDER> ViewORDER { get; set; }
    
        public virtual ObjectResult<GetOrderStatistics_Result> GetOrderStatistics(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderStatistics_Result>("GetOrderStatistics", startDateParameter, endDateParameter);
        }
    }
}
