//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.BILLS = new HashSet<BILLS>();
        }
    
        public int ID_ORDER { get; set; }
        public int ID_USER { get; set; }
        public int ID_PRODUCT { get; set; }
        public int ID_EMPLOYEE { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public int NUMBER { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLS> BILLS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
