//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewORDER
    {
        public string PRODUCTSNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public int NUMBER { get; set; }
        public Nullable<System.DateTime> ORDERTIME { get; set; }
        public string USERSURNAME { get; set; }
        public string USERNAME { get; set; }
        public string PATRONYMIC { get; set; }
        public string PHONE { get; set; }
        public string EMPLOYEESURNAME { get; set; }
        public string POST { get; set; }
        public Nullable<decimal> ORDERSUM { get; set; }
    }
}
